FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app
EXPOSE 80
COPY Shared/SportStore.Shared/*.csproj Shared/SportStore.Shared/
COPY Services/FakePayment/SportStore.Services.FakePayment/*.csproj Services/FakePayment/SportStore.Services.FakePayment/
RUN dotnet restore Services/FakePayment/SportStore.Services.FakePayment/*.csproj
COPY . .
RUN dotnet publish Services/FakePayment/SportStore.Services.FakePayment/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","SportStore.Services.FakePayment.dll" ]
