FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app
EXPOSE 80
COPY Shared/SportStore.Shared/*.csproj Shared/SportStore.Shared/
COPY Frontends/SportStore.Web/*.csproj Frontends/SportStore.Web/
RUN dotnet restore Frontends/SportStore.Web/*.csproj
COPY . .
RUN dotnet publish Frontends/SportStore.Web/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet","SportStore.Web.dll" ]
